"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '$all$directory$character'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[kubernetes]
disabled = false
symbol = '☸'
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "󰋑" },
]
format = '[$symbol $context|$namespace ](fg:green)($style)'

[terraform]
symbol = '󱁢'
format = '[$symbol $version]($style) '

[git_branch]
symbol = " "

[git_status]
format = '[($all_status$ahead_behind) ]($style)'
conflicted = '='
ahead = '[⇡${count}](green)'
behind = '[⇣${count}](red)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](yellow)'
up_to_date = '[✓](green)'
untracked = '?'
stashed = '[\$](yellow)'
modified = '!'
staged = '[++\($count\)](green)'
renamed = '»'
deleted = '✘'
typechanged = ''
ignore_submodules = false

[package]
symbol = "󰏗 "

[nodejs]
symbol = " "

[c]
symbol = " "

[rust]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[python]
symbol = " "

[docker_context]
disabled = true
symbol = ""

[conda]
symbol = " "

[lua]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'
